name: Pull Request Checks

on: [pull_request]

jobs:
  checks:
    name: Preview Checks and Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run the build
        run: npm run build

      - name: Run Unit Tests
        run: npm test
